###

TOP   = $(abspath $(dir $(filter %Makefile.common,$(MAKEFILE_LIST)))../)
TEST  = $(TOP)/test/
CDIR  = $(abspath $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
RDIR  = $(subst $(TEST),,$(CDIR))
SDIR  = $(TOP)/src/$(RDIR)
SIDIR = $(SDIR)/include
BINS  = $(SRCS:%.c=%)
RND   = $(TOP)/ext/randombytes/randombytes.c
CFLAGS := -O3 -Wall

#

default: $(BINS)

run: $(BINS)
	for b in $(BINS); do (echo $$b && ./$$b); done

clean:
	rm -f $(BINS)

##

$(BINS):
	make -C $(SDIR)
	$(CC) $(CFLAGS) -o $@ $@.c -I$(SIDIR) $(SDIR)/*.s $(RND)


