#!/bin/bash

timeout=20

ECO=
#ECO=-no-eco

check() {
  echo checking $1;
  if easycrypt $ECO -p "CVC4"  -p "Z3" -p "Alt-Ergo"  -I ./proof -I ./proof/eclib -I ./proof/montgomery_ladder -I ./proof/rejection_sampling -timeout $timeout $1;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

# list of files to check

## Montgomery ladder
check proof/montgomery_ladder/Ith_Bit64.ec
check proof/montgomery_ladder/ML_step_1.ec
check proof/montgomery_ladder/ML_step_2.ec
check proof/montgomery_ladder/ML_step_3.ec
check proof/montgomery_ladder/ML_step_4.ec
check proof/montgomery_ladder/ML_step_5.ec
check proof/montgomery_ladder/ML_step_6.ec
check proof/montgomery_ladder/ML_step_7.ec
check proof/montgomery_ladder/MontgomeryLadder.ec

## rejection sampling
check proof/rejection_sampling/RejectionSamplingCorrectness.ec
check proof/rejection_sampling/RejectionSampling.ec
check proof/rejection_sampling/RejectionSamplingIndexed.ec
check proof/rejection_sampling/RejectionSamplingModule.ec
check proof/rejection_sampling/RejectionSamplingProperties.ec


## misc
check proof/BarrettRedInt.ec
check proof/Ring_ops_extract.ec
check proof/Ring_ops_extract_ct.ec
check proof/Ring_ops_proof.ec
check proof/Ring_ops_proof_ct.ec
check proof/Ring_ops_spec.ec
check proof/Uniform_distr_extract_ct.ec
check proof/Uniform_distr_proof_ct.ec


echo "DONE";
