name: main

on:
  workflow_dispatch:
  push:
    branches:
      - deploy/ci
  pull_request:

jobs:

  compile:
    runs-on: [self-hosted, linux, X64, amd64-main]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: compile and run
        run: JASMIN=$(which_jasminc) make -C src/ compile_and_run

      - name: check all
        run: JASMIN=$(which_jasminc) make -C src/ make check_all

